#pragma once

#include <array>
#include <ruvia/web/db/DbMigration.h>

namespace service::config {

inline constexpr std::array<ruvia::DbMigration, 13> kSchemaMigrations{{
    {"0000_enable_timescaledb", R"sql(
CREATE EXTENSION IF NOT EXISTS timescaledb;
)sql"},
    {"0001_create_system_roles", R"sql(
CREATE TABLE IF NOT EXISTS sys_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64) NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(500),
    status      VARCHAR(20) NOT NULL DEFAULT 'enabled',
    permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);
)sql"},
    {"0002_create_system_users", R"sql(
CREATE TABLE IF NOT EXISTS sys_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname      VARCHAR(100),
    phone         VARCHAR(20),
    email         VARCHAR(100),
    status        VARCHAR(20) NOT NULL DEFAULT 'enabled',
    profile       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ
);
)sql"},
    {"0003_create_system_user_roles", R"sql(
CREATE TABLE IF NOT EXISTS sys_user_role (
    user_id BIGINT NOT NULL REFERENCES sys_user(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES sys_role(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
)sql"},
    {"0004_index_system_user_status", R"sql(
CREATE INDEX IF NOT EXISTS idx_sys_user_status ON sys_user(status) WHERE deleted_at IS NULL;
)sql"},
    {"0005_index_system_user_username", R"sql(
CREATE INDEX IF NOT EXISTS idx_sys_user_username ON sys_user(username) WHERE deleted_at IS NULL;
)sql"},
    {"0006_index_system_role_permissions", R"sql(
CREATE INDEX IF NOT EXISTS idx_sys_role_permissions ON sys_role USING GIN(permissions);
)sql"},
    {"0007_seed_superadmin_role", R"sql(
INSERT INTO sys_role(code, name, description, status, permissions)
VALUES ('superadmin', '超级管理员', '系统内置角色', 'enabled', '["*"]'::jsonb)
ON CONFLICT (code) DO NOTHING;
)sql"},
    {"0008_seed_admin_user", R"sql(
INSERT INTO sys_user(username, password_hash, nickname, status)
VALUES (
    'admin',
    'pbkdf2_sha256$210000$c92f36ef05a2afc548b868057a91af3a$9aa29710cf82ac0a23c8b0a112e76e2b860ecb303c949b9eada7045762df5974',
    '系统管理员',
    'enabled'
)
ON CONFLICT (username) DO NOTHING;
)sql"},
    {"0009_bind_superadmin", R"sql(
INSERT INTO sys_user_role(user_id, role_id)
SELECT u.id, r.id
FROM sys_user u, sys_role r
WHERE u.username = 'admin' AND r.code = 'superadmin'
ON CONFLICT DO NOTHING;
)sql"},
    {"0011_create_system_departments", R"sql(
CREATE TABLE IF NOT EXISTS sys_dept (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    code        VARCHAR(64) UNIQUE,
    parent_id   BIGINT REFERENCES sys_dept(id) ON DELETE RESTRICT,
    leader_id   BIGINT REFERENCES sys_user(id) ON DELETE SET NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    status      VARCHAR(20) NOT NULL DEFAULT 'enabled',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);
)sql"},
    {"0012_index_system_dept_parent", R"sql(
CREATE INDEX IF NOT EXISTS idx_sys_dept_parent ON sys_dept(parent_id, sort_order)
WHERE deleted_at IS NULL;
)sql"},
    {"0013_index_system_dept_status", R"sql(
CREATE INDEX IF NOT EXISTS idx_sys_dept_status ON sys_dept(status) WHERE deleted_at IS NULL;
)sql"},
}};

} // namespace service::config
