#pragma once

#include <array>
#include <ruvia/web/db/DbMigration.h>

namespace service::config {

inline constexpr std::array<ruvia::DbMigration, 11> kSchemaMigrations{{
    {"0001_enable_timescaledb", R"sql(
CREATE EXTENSION IF NOT EXISTS timescaledb;
)sql"},
    {"0002_create_system_roles", R"sql(
CREATE TABLE IF NOT EXISTS sys_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64) NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(500),
    status      VARCHAR(20) NOT NULL DEFAULT 'enabled'
                CHECK (status IN ('enabled', 'disabled')),
    permissions JSONB NOT NULL DEFAULT '[]'::jsonb
                CHECK (jsonb_typeof(permissions) = 'array'),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);
)sql"},
    {"0003_create_system_users", R"sql(
CREATE TABLE IF NOT EXISTS sys_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname      VARCHAR(100),
    phone         VARCHAR(20),
    email         VARCHAR(100),
    status        VARCHAR(20) NOT NULL DEFAULT 'enabled'
                  CHECK (status IN ('enabled', 'disabled')),
    profile       JSONB NOT NULL DEFAULT '{}'::jsonb
                  CHECK (jsonb_typeof(profile) = 'object'),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ
);
)sql"},
    {"0004_create_system_user_roles", R"sql(
CREATE TABLE IF NOT EXISTS sys_user_role (
    user_id BIGINT NOT NULL REFERENCES sys_user(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES sys_role(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
)sql"},
    {"0005_create_system_departments", R"sql(
CREATE TABLE IF NOT EXISTS sys_dept (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    code        VARCHAR(64) UNIQUE,
    parent_id   BIGINT REFERENCES sys_dept(id) ON DELETE RESTRICT,
    leader_id   BIGINT REFERENCES sys_user(id) ON DELETE SET NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    status      VARCHAR(20) NOT NULL DEFAULT 'enabled'
                CHECK (status IN ('enabled', 'disabled')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);
)sql"},
    {"0006_seed_system_admin", R"sql(
WITH role_row AS (
    INSERT INTO sys_role(code, name, description, status, permissions)
    VALUES ('superadmin', '超级管理员', '系统内置角色', 'enabled', '["*"]'::jsonb)
    ON CONFLICT (code) DO UPDATE SET code = EXCLUDED.code
    RETURNING id
), user_row AS (
    INSERT INTO sys_user(username, password_hash, nickname, status)
    VALUES (
        'admin',
        'pbkdf2_sha256$210000$c92f36ef05a2afc548b868057a91af3a$9aa29710cf82ac0a23c8b0a112e76e2b860ecb303c949b9eada7045762df5974',
        '系统管理员',
        'enabled'
    )
    ON CONFLICT (username) DO UPDATE SET username = EXCLUDED.username
    RETURNING id
)
INSERT INTO sys_user_role(user_id, role_id)
SELECT user_row.id, role_row.id FROM user_row CROSS JOIN role_row
ON CONFLICT DO NOTHING;
)sql"},
    {"0007_create_iot_links", R"sql(
CREATE TABLE IF NOT EXISTS iot_link (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    mode        VARCHAR(20) NOT NULL CHECK (mode IN ('TCP Server', 'TCP Client')),
    protocol    VARCHAR(20) NOT NULL CHECK (protocol IN ('SL651', 'Modbus', 'S7')),
    ip          VARCHAR(50) NOT NULL DEFAULT '',
    port        INTEGER NOT NULL DEFAULT 0 CHECK (port BETWEEN 0 AND 65535),
    targets     JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(targets) = 'array'),
    status      VARCHAR(20) NOT NULL DEFAULT 'enabled'
                CHECK (status IN ('enabled', 'disabled')),
    created_by  BIGINT NOT NULL REFERENCES sys_user(id) ON DELETE RESTRICT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT ck_iot_link_endpoint CHECK (
        (mode = 'TCP Server' AND ip <> '' AND port BETWEEN 1 AND 65535
         AND jsonb_array_length(targets) = 0)
        OR
        (mode = 'TCP Client' AND ip = '' AND port = 0
         AND jsonb_array_length(targets) > 0)
    )
);
)sql"},
    {"0008_create_iot_protocol_configs", R"sql(
CREATE TABLE IF NOT EXISTS iot_protocol_config (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol    VARCHAR(20) NOT NULL CHECK (protocol IN ('SL651', 'Modbus', 'S7')),
    name        VARCHAR(64) NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    config      JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config) = 'object'),
    remark      TEXT,
    created_by  BIGINT NOT NULL REFERENCES sys_user(id) ON DELETE RESTRICT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);
)sql"},
    {"0009_create_iot_device_groups", R"sql(
CREATE TABLE IF NOT EXISTS iot_device_group (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    parent_id   BIGINT REFERENCES iot_device_group(id) ON DELETE RESTRICT,
    status      VARCHAR(20) NOT NULL DEFAULT 'enabled'
                CHECK (status IN ('enabled', 'disabled')),
    sort_order  INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    remark      TEXT,
    created_by  BIGINT NOT NULL REFERENCES sys_user(id) ON DELETE RESTRICT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);
)sql"},
    {"0010_create_iot_devices", R"sql(
CREATE TABLE IF NOT EXISTS iot_device (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    device_code         VARCHAR(100) NOT NULL CHECK (device_code ~ '^[A-Za-z0-9]+$'),
    link_id             BIGINT NOT NULL REFERENCES iot_link(id) ON DELETE RESTRICT,
    target_id           VARCHAR(100),
    protocol_config_id  BIGINT NOT NULL REFERENCES iot_protocol_config(id) ON DELETE RESTRICT,
    group_id            BIGINT REFERENCES iot_device_group(id) ON DELETE RESTRICT,
    status              VARCHAR(20) NOT NULL DEFAULT 'enabled'
                        CHECK (status IN ('enabled', 'disabled')),
    online_timeout      INTEGER NOT NULL DEFAULT 300 CHECK (online_timeout BETWEEN 1 AND 86400),
    remote_control      BOOLEAN NOT NULL DEFAULT TRUE,
    modbus_mode         VARCHAR(10) CHECK (modbus_mode IS NULL OR modbus_mode IN ('TCP', 'RTU')),
    slave_id            INTEGER CHECK (slave_id IS NULL OR slave_id BETWEEN 1 AND 247),
    timezone            VARCHAR(6) NOT NULL DEFAULT '+08:00',
    heartbeat           JSONB NOT NULL DEFAULT '{"mode":"OFF"}'::jsonb
                        CHECK (jsonb_typeof(heartbeat) = 'object'),
    registration        JSONB NOT NULL DEFAULT '{"mode":"OFF"}'::jsonb
                        CHECK (jsonb_typeof(registration) = 'object'),
    remark              TEXT,
    created_by          BIGINT NOT NULL REFERENCES sys_user(id) ON DELETE RESTRICT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMPTZ
);
)sql"},
    {"0011_force_database_utc", R"sql(
DO $migration$
BEGIN
    EXECUTE format('ALTER DATABASE %I SET timezone TO %L', current_database(), 'UTC');
    PERFORM set_config('TimeZone', 'UTC', false);
END
$migration$;
)sql"},
}};

} // namespace service::config
