cmake_minimum_required(VERSION 3.25)

if(NOT WIN32)
  message(FATAL_ERROR "WinUI packaging requires Windows.")
endif()

if(NOT DEFINED BUILD_ROOT OR NOT DEFINED SOURCE_ROOT OR NOT DEFINED LOCK_FILE)
  message(FATAL_ERROR "BUILD_ROOT, SOURCE_ROOT and LOCK_FILE are required.")
endif()

function(run_checked)
  execute_process(
    COMMAND ${ARGV}
    RESULT_VARIABLE _result
    OUTPUT_VARIABLE _stdout
    ERROR_VARIABLE _stderr)
  if(_stdout)
    message(STATUS "${_stdout}")
  endif()
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGV}\n${_stderr}")
  endif()
endfunction()

function(json_value output json)
  set(_path ${ARGN})
  string(JSON _value GET "${json}" ${_path})
  set(${output} "${_value}" PARENT_SCOPE)
endfunction()

function(xml_escape output value)
  set(_value "${value}")
  string(REPLACE "&" "&amp;" _value "${_value}")
  string(REPLACE "<" "&lt;" _value "${_value}")
  string(REPLACE ">" "&gt;" _value "${_value}")
  string(REPLACE "\"" "&quot;" _value "${_value}")
  string(REPLACE "'" "&apos;" _value "${_value}")
  set(${output} "${_value}" PARENT_SCOPE)
endfunction()

function(assert_safe_delete target allowed_root)
  get_filename_component(_target_abs "${target}" ABSOLUTE)
  get_filename_component(_root_abs "${allowed_root}" ABSOLUTE)
  if(NOT EXISTS "${_root_abs}")
    message(FATAL_ERROR "Deletion root does not exist: ${_root_abs}")
  endif()
  file(REAL_PATH "${_root_abs}" _root_real)
  if(EXISTS "${_target_abs}")
    if(IS_SYMLINK "${_target_abs}")
      message(FATAL_ERROR "Refusing to delete a reparse point: ${_target_abs}")
    endif()
    file(REAL_PATH "${_target_abs}" _target_real)
  else()
    get_filename_component(_parent "${_target_abs}" DIRECTORY)
    if(NOT EXISTS "${_parent}")
      message(FATAL_ERROR "Deletion target parent does not exist: ${_parent}")
    endif()
    file(REAL_PATH "${_parent}" _parent_real)
    get_filename_component(_name "${_target_abs}" NAME)
    set(_target_real "${_parent_real}/${_name}")
  endif()
  string(TOLOWER "${_root_real}" _root_lower)
  string(TOLOWER "${_target_real}" _target_lower)
  string(LENGTH "${_root_lower}" _root_length)
  string(SUBSTRING "${_target_lower}" 0 ${_root_length} _target_prefix)
  string(SUBSTRING "${_target_lower}" ${_root_length} -1 _target_suffix)
  if(_target_lower STREQUAL "${_root_lower}" OR
     NOT _target_prefix STREQUAL "${_root_lower}" OR
     NOT _target_suffix MATCHES "^/")
    message(FATAL_ERROR "Deletion target escapes its build root: ${_target_abs}")
  endif()
endfunction()

function(download_package output archive url expected)
  if(EXISTS "${archive}")
    file(SHA256 "${archive}" _actual)
    if(NOT _actual STREQUAL "${expected}")
      file(REMOVE "${archive}")
    endif()
  endif()
  if(NOT EXISTS "${archive}")
    file(DOWNLOAD "${url}" "${archive}"
      EXPECTED_HASH "SHA256=${expected}"
      STATUS _download_status)
    list(GET _download_status 0 _download_code)
    if(NOT _download_code EQUAL 0)
      message(FATAL_ERROR "NuGet package download failed: ${_download_status}")
    endif()
  endif()
  set(${output} "${archive}" PARENT_SCOPE)
endfunction()

file(READ "${LOCK_FILE}" _lock_json)
string(JSON _package_count LENGTH "${_lock_json}")
set(_packages_root "${BUILD_ROOT}/windows-winui-tools/packages")
file(MAKE_DIRECTORY "${_packages_root}")
math(EXPR _last_package "${_package_count} - 1")
if(_package_count GREATER 0)
  foreach(_index RANGE 0 ${_last_package})
    json_value(_id "${_lock_json}" ${_index} id)
    json_value(_version "${_lock_json}" ${_index} version)
    json_value(_expected "${_lock_json}" ${_index} sha256)
    string(TOLOWER "${_id}" _lower_id)
    set(_name "${_id}.${_version}")
    set(_folder "${_packages_root}/${_name}")
    set(_archive "${_folder}/${_name}.nupkg")
    set(_marker "${_folder}/.archive-sha256")
    if(EXISTS "${_marker}")
      file(READ "${_marker}" _marker_value)
      string(STRIP "${_marker_value}" _marker_value)
    else()
      set(_marker_value "")
    endif()
    if(NOT _marker_value STREQUAL "${_expected}" OR NOT EXISTS "${_folder}/build")
      assert_safe_delete("${_folder}" "${_packages_root}")
      file(MAKE_DIRECTORY "${_folder}")
      download_package(_pinned_archive "${_archive}"
        "https://api.nuget.org/v3-flatcontainer/${_lower_id}/${_version}/${_lower_id}.${_version}.nupkg"
        "${_expected}")
      set(_extract "${_packages_root}/.${_name}.extract")
      assert_safe_delete("${_extract}" "${_packages_root}")
      file(REMOVE_RECURSE "${_extract}")
      file(MAKE_DIRECTORY "${_extract}")
      file(ARCHIVE_EXTRACT INPUT "${_pinned_archive}" DESTINATION "${_extract}")
      assert_safe_delete("${_folder}" "${_packages_root}")
      file(REMOVE_RECURSE "${_folder}")
      file(MAKE_DIRECTORY "${_folder}")
      file(COPY "${_extract}/" DESTINATION "${_folder}")
      file(REMOVE_RECURSE "${_extract}")
      file(WRITE "${_marker}" "${_expected}\n")
    endif()
  endforeach()
endif()

set(_imports_root "${BUILD_ROOT}/windows-winui-tools/packages")
foreach(_extension IN ITEMS props targets)
  set(_imports "${_imports_root}/imports.${_extension}")
  file(WRITE "${_imports}" "<Project xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\n")
  if(_package_count GREATER 0)
    foreach(_index RANGE 0 ${_last_package})
      json_value(_id "${_lock_json}" ${_index} id)
      json_value(_version "${_lock_json}" ${_index} version)
      set(_folder "${_packages_root}/${_id}.${_version}")
      set(_path "${_folder}/build/native/${_id}.${_extension}")
      if(NOT EXISTS "${_path}")
        set(_path "${_folder}/build/${_id}.${_extension}")
      endif()
      if(EXISTS "${_path}")
        file(TO_NATIVE_PATH "${_path}" _native_path)
        xml_escape(_escaped_path "${_native_path}")
        file(APPEND "${_imports}" "  <Import Project=\"${_escaped_path}\" />\n")
      endif()
    endforeach()
  endif()
  file(APPEND "${_imports}" "</Project>\n")
endforeach()

find_program(_vswhere NAMES vswhere.exe vswhere
  PATHS
    "$ENV{ProgramFiles}/../Program Files (x86)/Microsoft Visual Studio/Installer"
    "$ENV{ProgramFiles}/Microsoft Visual Studio/Installer")
if(NOT _vswhere)
  message(FATAL_ERROR "Visual Studio vswhere.exe is required.")
endif()
if(NOT _vswhere)
  message(FATAL_ERROR "Visual Studio vswhere.exe is required.")
endif()
execute_process(
  COMMAND "${_vswhere}" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
  RESULT_VARIABLE _vs_result
  OUTPUT_VARIABLE _vs
  ERROR_VARIABLE _vs_error
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT _vs_result EQUAL 0 OR NOT _vs)
  message(FATAL_ERROR "Visual Studio 2022 C++ Build Tools are required: ${_vs_error}")
endif()
set(_msbuild "${_vs}/MSBuild/Current/Bin/MSBuild.exe")
if(NOT EXISTS "${_msbuild}")
  message(FATAL_ERROR "MSBuild.exe is missing: ${_msbuild}")
endif()
run_checked("${_msbuild}" "${SOURCE_ROOT}/winui/iot-egine.vcxproj"
  /p:Configuration=Release /p:Platform=x64 /m:4 /v:minimal /nologo)

set(_output "${BUILD_ROOT}/windows-winui/Release")
if(NOT EXISTS "${_output}/iot-egine.exe")
  message(FATAL_ERROR "WinUI build did not produce ${_output}/iot-egine.exe")
endif()
file(GLOB _crt_candidates LIST_DIRECTORIES true
  "${_vs}/VC/Redist/MSVC/*/x64/Microsoft.VC143.CRT")
list(SORT _crt_candidates ORDER DESCENDING)
list(LENGTH _crt_candidates _crt_count)
if(_crt_count EQUAL 0)
  message(FATAL_ERROR "MSVC redistributable runtime is missing.")
endif()
list(GET _crt_candidates 0 _crt)
file(GLOB _crt_dlls "${_crt}/*.dll")
foreach(_dll IN LISTS _crt_dlls)
  get_filename_component(_dll_name "${_dll}" NAME)
  file(COPY_FILE "${_dll}" "${_output}/${_dll_name}" ONLY_IF_DIFFERENT)
endforeach()
message(STATUS "C++ WinUI 3 output: ${_output}")
