cmake_minimum_required(VERSION 3.25)

if(NOT WIN32)
  message(FATAL_ERROR "WireGuard native packaging requires Windows.")
endif()

if(NOT DEFINED BUILD_ROOT OR NOT DEFINED SOURCE_ROOT OR NOT DEFINED LOCK_FILE)
  message(FATAL_ERROR "BUILD_ROOT, SOURCE_ROOT and LOCK_FILE are required.")
endif()

function(run_checked)
  execute_process(
    COMMAND ${ARGV}
    RESULT_VARIABLE _result
    OUTPUT_VARIABLE _stdout
    ERROR_VARIABLE _stderr)
  if(_stdout)
    message(STATUS "${_stdout}")
  endif()
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Command failed (${_result}): ${ARGV}\n${_stderr}")
  endif()
endfunction()

function(json_value output json)
  set(_path ${ARGN})
  string(JSON _value GET "${json}" ${_path})
  set(${output} "${_value}" PARENT_SCOPE)
endfunction()

function(assert_safe_delete target allowed_root)
  get_filename_component(_target_abs "${target}" ABSOLUTE)
  get_filename_component(_root_abs "${allowed_root}" ABSOLUTE)
  if(NOT EXISTS "${_root_abs}")
    message(FATAL_ERROR "Deletion root does not exist: ${_root_abs}")
  endif()
  file(REAL_PATH "${_root_abs}" _root_real)
  if(EXISTS "${_target_abs}")
    if(IS_SYMLINK "${_target_abs}")
      message(FATAL_ERROR "Refusing to delete a reparse point: ${_target_abs}")
    endif()
    file(REAL_PATH "${_target_abs}" _target_real)
  else()
    get_filename_component(_parent "${_target_abs}" DIRECTORY)
    if(NOT EXISTS "${_parent}")
      message(FATAL_ERROR "Deletion target parent does not exist: ${_parent}")
    endif()
    file(REAL_PATH "${_parent}" _parent_real)
    get_filename_component(_name "${_target_abs}" NAME)
    set(_target_real "${_parent_real}/${_name}")
  endif()
  string(TOLOWER "${_root_real}" _root_lower)
  string(TOLOWER "${_target_real}" _target_lower)
  string(LENGTH "${_root_lower}" _root_length)
  string(SUBSTRING "${_target_lower}" 0 ${_root_length} _target_prefix)
  string(SUBSTRING "${_target_lower}" ${_root_length} -1 _target_suffix)
  if(_target_lower STREQUAL "${_root_lower}" OR
     NOT _target_prefix STREQUAL "${_root_lower}" OR
     NOT _target_suffix MATCHES "^/")
    message(FATAL_ERROR "Deletion target escapes its build root: ${_target_abs}")
  endif()
endfunction()

function(download_pinned output name url expected)
  set(_archive "${_build_root}/${name}.zip")
  if(EXISTS "${_archive}")
    file(SHA256 "${_archive}" _actual)
    if(NOT _actual STREQUAL "${expected}")
      file(REMOVE "${_archive}")
    endif()
  endif()
  if(NOT EXISTS "${_archive}")
    file(DOWNLOAD "${url}" "${_archive}"
      EXPECTED_HASH "SHA256=${expected}"
      STATUS _download_status)
    list(GET _download_status 0 _download_code)
    if(NOT _download_code EQUAL 0)
      message(FATAL_ERROR "Pinned ${name} download failed: ${_download_status}")
    endif()
  endif()
  set(${output} "${_archive}" PARENT_SCOPE)
endfunction()

function(extract_pinned output name archive expected)
  set(_destination "${_build_root}/${name}")
  set(_marker "${_destination}/.archive-sha256")
  if(EXISTS "${_marker}")
    file(READ "${_marker}" _marker_value)
    string(STRIP "${_marker_value}" _marker_value)
    if(_marker_value STREQUAL "${expected}")
      set(${output} "${_destination}" PARENT_SCOPE)
      return()
    endif()
  endif()
  assert_safe_delete("${_destination}" "${_build_root}")
  file(REMOVE_RECURSE "${_destination}")
  file(MAKE_DIRECTORY "${_destination}")
  find_program(_tar NAMES tar.exe tar)
  if(NOT _tar)
    message(FATAL_ERROR "tar.exe is required to unpack pinned WireGuard archives.")
  endif()
  run_checked("${_tar}" -xf "${archive}" -C "${_destination}" --strip-components 1)
  file(WRITE "${_marker}" "${expected}\n")
  set(${output} "${_destination}" PARENT_SCOPE)
endfunction()

file(READ "${LOCK_FILE}" _lock_json)
json_value(_repository "${_lock_json}" repository)
json_value(_revision "${_lock_json}" revision)
json_value(_go_url "${_lock_json}" go url)
json_value(_go_hash "${_lock_json}" go sha256)
json_value(_mingw_url "${_lock_json}" mingw url)
json_value(_mingw_hash "${_lock_json}" mingw sha256)
json_value(_driver_url "${_lock_json}" driver url)
json_value(_driver_hash "${_lock_json}" driver sha256)

set(_build_root "${BUILD_ROOT}/windows-vpn-native")
set(_source "${_build_root}/source")
file(MAKE_DIRECTORY "${_build_root}")

if(NOT EXISTS "${_source}/.git")
  run_checked(git clone --no-checkout "${_repository}" "${_source}")
endif()
execute_process(
  COMMAND git -C "${_source}" status --porcelain --untracked-files=no
  RESULT_VARIABLE _status_result
  OUTPUT_VARIABLE _dirty
  ERROR_VARIABLE _status_error
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT _status_result EQUAL 0 OR _dirty)
  message(FATAL_ERROR "WireGuard source checkout contains local edits: ${_dirty}${_status_error}")
endif()
run_checked(git -C "${_source}" checkout --detach "${_revision}")
execute_process(
  COMMAND git -C "${_source}" rev-parse HEAD
  RESULT_VARIABLE _revision_result
  OUTPUT_VARIABLE _actual_revision
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT _revision_result EQUAL 0 OR NOT _actual_revision STREQUAL "${_revision}")
  message(FATAL_ERROR "Wrong WireGuard source revision: ${_actual_revision}")
endif()

download_pinned(_go_archive go "${_go_url}" "${_go_hash}")
download_pinned(_mingw_archive mingw "${_mingw_url}" "${_mingw_hash}")
download_pinned(_driver_archive driver "${_driver_url}" "${_driver_hash}")
extract_pinned(_go_root go "${_go_archive}" "${_go_hash}")
extract_pinned(_mingw_root mingw "${_mingw_archive}" "${_mingw_hash}")
extract_pinned(_driver_root driver "${_driver_archive}" "${_driver_hash}")

set(_native_output "${_build_root}/output")
assert_safe_delete("${_native_output}" "${_build_root}")
file(REMOVE_RECURSE "${_native_output}")
file(MAKE_DIRECTORY "${_native_output}")
file(MAKE_DIRECTORY "${_build_root}/gopath")
set(_go "${_go_root}/bin/go.exe")
set(_cc "${_mingw_root}/bin/x86_64-w64-mingw32-gcc.exe")
if(NOT EXISTS "${_go}" OR NOT EXISTS "${_cc}")
  message(FATAL_ERROR "Pinned Go or MinGW toolchain is incomplete.")
endif()
set(ENV{PATH} "${_mingw_root}/bin;${_go_root}/bin;$ENV{PATH}")
set(ENV{GOROOT} "${_go_root}")
set(ENV{GOPATH} "${_build_root}/gopath")
set(ENV{GOOS} windows)
set(ENV{GOARCH} amd64)
set(ENV{CGO_ENABLED} 1)
set(ENV{CC} "${_cc}")
set(ENV{CGO_CFLAGS} "-O3 -Wall -Wno-unused-function -Wno-switch -std=gnu11 -DWINVER=0x0A00")
execute_process(
  COMMAND "${_go}" build -buildmode=c-shared "-ldflags=-w -s" -trimpath -buildvcs=false
    -o "${_native_output}/tunnel.dll" .
  WORKING_DIRECTORY "${_source}/embeddable-dll-service"
  RESULT_VARIABLE _go_result
  OUTPUT_VARIABLE _go_output
  ERROR_VARIABLE _go_error)
if(_go_output)
  message(STATUS "${_go_output}")
endif()
if(NOT _go_result EQUAL 0)
  message(FATAL_ERROR "WireGuard tunnel build failed (${_go_result}): ${_go_error}")
endif()

set(_driver_dll "${_driver_root}/wireguard-nt/bin/amd64/wireguard.dll")
if(NOT EXISTS "${_driver_dll}")
  message(FATAL_ERROR "Pinned WireGuardNT driver is missing: ${_driver_dll}")
endif()
find_program(_signtool NAMES signtool.exe signtool)
if(_signtool)
  run_checked("${_signtool}" verify /pa /q "${_driver_dll}")
else()
  message(STATUS "signtool.exe was not found; ServiceControl will verify the driver signature during package validation.")
endif()
file(COPY_FILE "${_driver_dll}" "${_native_output}/wireguard.dll")
file(COPY_FILE "${_source}/COPYING" "${_native_output}/WireGuard-Windows-LICENSE.txt")
file(COPY_FILE "${_go_root}/LICENSE" "${_native_output}/Go-LICENSE.txt")
file(GLOB _module_dirs LIST_DIRECTORIES true "${_build_root}/gopath/pkg/mod/golang.org/x/*")
foreach(_module IN LISTS _module_dirs)
  if(IS_DIRECTORY "${_module}" AND EXISTS "${_module}/LICENSE")
    get_filename_component(_module_name "${_module}" NAME)
    file(COPY_FILE "${_module}/LICENSE" "${_native_output}/${_module_name}-LICENSE.txt")
  endif()
endforeach()
if(EXISTS "${_driver_root}/wireguard-nt/LICENSE.txt")
  file(COPY_FILE "${_driver_root}/wireguard-nt/LICENSE.txt" "${_native_output}/WireGuardNT-LICENSE.txt")
endif()
file(COPY_FILE "${LOCK_FILE}" "${_native_output}/wireguard.lock.json")
message(STATUS "WireGuard native files: ${_native_output}")
