cmake_minimum_required(VERSION 3.25)

if(NOT WIN32)
  message(FATAL_ERROR "Windows client packaging requires Windows.")
endif()

foreach(_required IN ITEMS BUILD_ROOT SOURCE_ROOT NATIVE_BUILD_DIRECTORY NATIVE_OUTPUT WINUI_OUTPUT PACKAGE_DIRECTORY CLIENT_CONFIG VERSION LOCK_FILE WINUI_LOCK_FILE)
  if(NOT DEFINED ${_required})
    message(FATAL_ERROR "${_required} is required.")
  endif()
endforeach()

function(fail message_text)
  message(FATAL_ERROR "${message_text}")
endfunction()

function(json_value output json)
  set(_path ${ARGN})
  string(JSON _value GET "${json}" ${_path})
  set(${output} "${_value}" PARENT_SCOPE)
endfunction()

function(json_escape output value)
  set(_value "${value}")
  string(REPLACE "\\" "\\\\" _value "${_value}")
  string(REPLACE "\"" "\\\"" _value "${_value}")
  string(REPLACE "\r" "\\r" _value "${_value}")
  string(REPLACE "\n" "\\n" _value "${_value}")
  string(REPLACE "\t" "\\t" _value "${_value}")
  set(${output} "${_value}" PARENT_SCOPE)
endfunction()

function(assert_safe_delete target allowed_root)
  get_filename_component(_target_abs "${target}" ABSOLUTE)
  get_filename_component(_root_abs "${allowed_root}" ABSOLUTE)
  if(NOT EXISTS "${_root_abs}")
    message(FATAL_ERROR "Deletion root does not exist: ${_root_abs}")
  endif()
  file(REAL_PATH "${_root_abs}" _root_real)
  if(EXISTS "${_target_abs}")
    if(IS_SYMLINK "${_target_abs}")
      fail("Refusing to delete a reparse point: ${_target_abs}")
    endif()
    file(REAL_PATH "${_target_abs}" _target_real)
  else()
    get_filename_component(_parent "${_target_abs}" DIRECTORY)
    if(NOT EXISTS "${_parent}")
      fail("Deletion target parent does not exist: ${_parent}")
    endif()
    file(REAL_PATH "${_parent}" _parent_real)
    get_filename_component(_name "${_target_abs}" NAME)
    set(_target_real "${_parent_real}/${_name}")
  endif()
  string(TOLOWER "${_root_real}" _root_lower)
  string(TOLOWER "${_target_real}" _target_lower)
  string(LENGTH "${_root_lower}" _root_length)
  string(SUBSTRING "${_target_lower}" 0 ${_root_length} _target_prefix)
  string(SUBSTRING "${_target_lower}" ${_root_length} -1 _target_suffix)
  if(_target_lower STREQUAL "${_root_lower}" OR
     NOT _target_prefix STREQUAL "${_root_lower}" OR
     NOT _target_suffix MATCHES "^/")
    fail("Deletion target escapes its build root: ${_target_abs}")
  endif()
endfunction()

function(copy_required source destination_directory)
  if(NOT EXISTS "${source}")
    fail("Required client file is missing: ${source}")
  endif()
  file(MAKE_DIRECTORY "${destination_directory}")
  get_filename_component(_name "${source}" NAME)
  file(COPY_FILE "${source}" "${destination_directory}/${_name}")
endfunction()

file(TO_CMAKE_PATH "${BUILD_ROOT}" _build_root)
file(TO_CMAKE_PATH "${PACKAGE_DIRECTORY}" _package)
get_filename_component(_build_root "${_build_root}" ABSOLUTE)
get_filename_component(_package "${_package}" ABSOLUTE)
string(TOLOWER "${_build_root}" _build_root_lower)
string(TOLOWER "${_package}" _package_lower)
string(LENGTH "${_build_root_lower}" _build_length)
string(SUBSTRING "${_package_lower}" 0 ${_build_length} _package_prefix)
if(NOT _package_prefix STREQUAL "${_build_root_lower}" OR _package_lower STREQUAL "${_build_root_lower}")
  fail("Package output must stay inside the repository build directory: ${_package}")
endif()
string(SUBSTRING "${_package_lower}" ${_build_length} -1 _package_suffix)
if(NOT _package_suffix MATCHES "^/")
  fail("Package output must be a child of the repository build directory: ${_package}")
endif()

if(EXISTS "${_package}")
  if(NOT EXISTS "${_package}/manifest.json")
    fail("Refusing to clear a package directory without a generated manifest: ${_package}")
  endif()
  file(GLOB_RECURSE _entries LIST_DIRECTORIES true "${_package}/*" "${_package}/.*")
  foreach(_entry IN LISTS _entries)
    if(IS_SYMLINK "${_entry}")
      fail("Package path contains a reparse point: ${_entry}")
    endif()
  endforeach()
  assert_safe_delete("${_package}" "${_build_root}")
  file(REMOVE_RECURSE "${_package}")
endif()
file(MAKE_DIRECTORY "${_package}/Gui" "${_package}/Service" "${_package}/licenses")

set(_native_config "${NATIVE_BUILD_DIRECTORY}/${CLIENT_CONFIG}")
copy_required("${_native_config}/IotVpn.Service.exe" "${_package}/Service")
copy_required("${_native_config}/IotVpn.ServiceControl.exe" "${_package}/Service")
copy_required("${NATIVE_OUTPUT}/tunnel.dll" "${_package}/Service")
copy_required("${NATIVE_OUTPUT}/wireguard.dll" "${_package}/Service")
file(READ "${LOCK_FILE}" _wireguard_lock_json)
file(READ "${NATIVE_OUTPUT}/wireguard.lock.json" _native_wireguard_lock_json)
json_value(_wireguard_revision "${_wireguard_lock_json}" revision)
json_value(_wireguard_driver_hash "${_wireguard_lock_json}" driver sha256)
json_value(_native_wireguard_revision "${_native_wireguard_lock_json}" revision)
json_value(_native_wireguard_driver_hash "${_native_wireguard_lock_json}" driver sha256)
if(NOT _native_wireguard_revision STREQUAL "${_wireguard_revision}" OR
   NOT _native_wireguard_driver_hash STREQUAL "${_wireguard_driver_hash}")
  fail("WireGuard native output does not match wireguard.lock.json.")
endif()

file(GLOB_RECURSE _winui_files LIST_DIRECTORIES false "${WINUI_OUTPUT}/*")
list(SORT _winui_files)
set(_excluded_extensions ".pdb" ".ilk" ".lib" ".exp")
foreach(_file IN LISTS _winui_files)
  get_filename_component(_extension "${_file}" LAST_EXT)
  string(TOLOWER "${_extension}" _extension)
  get_filename_component(_name "${_file}" NAME)
  if(NOT _extension IN_LIST _excluded_extensions AND
     NOT _name STREQUAL "DirectML.dll" AND
     NOT _name STREQUAL "onnxruntime.dll" AND
     NOT _name STREQUAL "onnxruntime_providers_shared.dll")
    file(RELATIVE_PATH _relative "${WINUI_OUTPUT}" "${_file}")
    set(_target "${_package}/Gui/${_relative}")
    get_filename_component(_target_directory "${_target}" DIRECTORY)
    file(MAKE_DIRECTORY "${_target_directory}")
    file(COPY_FILE "${_file}" "${_target}")
  endif()
endforeach()
copy_required("${SOURCE_ROOT}/README.md" "${_package}")
copy_required("${LOCK_FILE}" "${_package}")

file(GLOB _native_licenses "${NATIVE_OUTPUT}/*LICENSE*")
foreach(_license IN LISTS _native_licenses)
  if(EXISTS "${_license}" AND NOT IS_DIRECTORY "${_license}")
    get_filename_component(_license_name "${_license}" NAME)
    file(COPY_FILE "${_license}" "${_package}/licenses/${_license_name}")
  endif()
endforeach()
copy_required("${SOURCE_ROOT}/native/vendor/LICENSE-json.txt" "${_package}/licenses")

file(READ "${WINUI_LOCK_FILE}" _winui_lock_json)
string(JSON _package_count LENGTH "${_winui_lock_json}")
math(EXPR _last_package "${_package_count} - 1")
if(_package_count GREATER 0)
  foreach(_index RANGE 0 ${_last_package})
    json_value(_id "${_winui_lock_json}" ${_index} id)
    json_value(_version "${_winui_lock_json}" ${_index} version)
    set(_dependency_folder "${BUILD_ROOT}/windows-winui-tools/packages/${_id}.${_version}")
    foreach(_license_name IN ITEMS license.txt NOTICE.txt)
      if(EXISTS "${_dependency_folder}/${_license_name}")
        file(COPY_FILE "${_dependency_folder}/${_license_name}"
          "${_package}/licenses/${_id}-${_license_name}")
      endif()
    endforeach()
  endforeach()
endif()

set(_manifest "{\n")
string(APPEND _manifest "  \"version\": \"${VERSION}\",\n")
string(APPEND _manifest "  \"platform\": \"win-x64\",\n")
string(APPEND _manifest "  \"language\": \"C++20\",\n")
string(APPEND _manifest "  \"ui\": \"C++/WinRT WinUI 3 Fluent\",\n")
string(APPEND _manifest "  \"installer\": \"WiX 6.0.2 Burn + MSI\",\n")
string(APPEND _manifest "  \"platformUrl\": \"https://i.a-z.xin\",\n")
file(READ "${LOCK_FILE}" _wireguard_lock_json)
json_value(_wireguard_revision "${_wireguard_lock_json}" revision)
string(APPEND _manifest "  \"wireguardRevision\": \"${_wireguard_revision}\",\n  \"files\": [\n")

file(GLOB_RECURSE _payload_files LIST_DIRECTORIES false "${_package}/*")
list(SORT _payload_files)
set(_file_index 0)
set(_runtime_extensions ".ps1" ".cmd" ".bat" ".js" ".vbs" ".cs")
foreach(_file IN LISTS _payload_files)
  get_filename_component(_extension "${_file}" LAST_EXT)
  string(TOLOWER "${_extension}" _extension)
  if(_extension IN_LIST _runtime_extensions)
    file(RELATIVE_PATH _relative "${_package}" "${_file}")
    fail("Runtime script found in package: ${_relative}")
  endif()
  file(RELATIVE_PATH _relative "${_package}" "${_file}")
  string(REPLACE "\\" "/" _relative "${_relative}")
  json_escape(_json_relative "${_relative}")
  file(SHA256 "${_file}" _hash)
  file(SIZE "${_file}" _bytes)
  if(_file_index GREATER 0)
    string(APPEND _manifest ",\n")
  endif()
  string(APPEND _manifest "    {\"path\": \"${_json_relative}\", \"sha256\": \"${_hash}\", \"bytes\": ${_bytes}}")
  math(EXPR _file_index "${_file_index} + 1")
endforeach()
string(APPEND _manifest "\n  ]\n}\n")
file(WRITE "${_package}/manifest.json" "${_manifest}")

set(_gui_report "${NATIVE_BUILD_DIRECTORY}/gui-package-check.txt")
file(REMOVE "${_gui_report}")
execute_process(
  COMMAND "${_package}/Gui/iot-egine.exe" --self-test --report "${_gui_report}"
  WORKING_DIRECTORY "${_package}/Gui"
  RESULT_VARIABLE _gui_result
  OUTPUT_VARIABLE _gui_output
  ERROR_VARIABLE _gui_error)
if(NOT _gui_result EQUAL 0)
  if(EXISTS "${_gui_report}")
    file(READ "${_gui_report}" _gui_report_text)
  endif()
  fail("Packaged GUI self-test failed (${_gui_result}): ${_gui_report_text}${_gui_error}")
endif()
if(EXISTS "${_gui_report}")
  file(READ "${_gui_report}" _gui_report_text)
  message(STATUS "${_gui_report_text}")
endif()

set(_service_report "${NATIVE_BUILD_DIRECTORY}/service-control-package-check.txt")
file(REMOVE "${_service_report}")
execute_process(
  COMMAND "${_package}/Service/IotVpn.ServiceControl.exe" --verify-files
    --root "${_package}" --report "${_service_report}"
  WORKING_DIRECTORY "${_package}/Service"
  RESULT_VARIABLE _service_result
  OUTPUT_VARIABLE _service_output
  ERROR_VARIABLE _service_error)
if(NOT _service_result EQUAL 0)
  if(EXISTS "${_service_report}")
    file(READ "${_service_report}" _service_report_text)
  endif()
  fail("Packaged binaries and driver validation failed (${_service_result}): ${_service_report_text}${_service_error}")
endif()
if(EXISTS "${_service_report}")
  file(READ "${_service_report}" _service_report_text)
  message(STATUS "${_service_report_text}")
endif()
message(STATUS "C++ WinUI package: ${_package}")
